INFO:root:start training
18/08/2020 01:29:05 PM  start training
18/08/2020 01:30:12 PM  start training
18/08/2020 01:48:53 PM  start training
18/08/2020 01:48:53 PM  hello
19/08/2020 05:29:02 AM  start training
19/08/2020 05:35:38 AM  start training
19/08/2020 05:36:14 AM  start training
19/08/2020 05:40:48 AM  start training
19/08/2020 04:58:24 PM  start training
19/08/2020 04:59:03 PM  start training
19/08/2020 04:59:15 PM  Speed: 0.08771 img/second, 2
19/08/2020 04:59:17 PM  Speed: 0.67435 img/second, 3
19/08/2020 04:59:19 PM  Speed: 0.52583 img/second, 4
19/08/2020 04:59:22 PM  Speed: 0.3291 img/second, 5
19/08/2020 04:59:23 PM  Speed: 0.66736 img/second, 6
19/08/2020 04:59:25 PM  Speed: 0.70298 img/second, 7
19/08/2020 04:59:29 PM  start training
19/08/2020 04:59:40 PM  Speed: 0.09981 img/second, 2
19/08/2020 04:59:41 PM  Speed: 0.74041 img/second, 3
19/08/2020 04:59:43 PM  Speed: 0.73936 img/second, 4
19/08/2020 04:59:46 PM  Speed: 0.35118 img/second, 5
19/08/2020 04:59:47 PM  Speed: 0.69358 img/second, 6
19/08/2020 04:59:49 PM  Speed: 0.69644 img/second, 7
19/08/2020 04:59:59 PM  start training
19/08/2020 05:00:12 PM  Speed: 0.08899 img/second, 2
19/08/2020 05:00:14 PM  Speed: 0.59775 img/second, 3
19/08/2020 05:00:16 PM  Speed: 0.65746 img/second, 4
19/08/2020 05:00:19 PM  Speed: 0.37168 img/second, 5
19/08/2020 05:00:25 PM  start training
19/08/2020 05:00:37 PM  Speed: 0.09614 img/second, 6
19/08/2020 05:00:39 PM  Speed: 0.64454 img/second, 7
19/08/2020 05:00:41 PM  Speed: 0.67322 img/second, 8
22/08/2020 01:31:52 AM  start training
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff14419bdd0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff1440b67d0>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff144060ad0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff1440b2dd0>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c744810> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c7a6510>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff11c749a90> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff1440ab5d0>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c768250> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c70b9d0>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c704550> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c768250>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff11c70d6d0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff144060bd0>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c6cdd50> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c734350>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c6d5fd0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c6eba10>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff11c76c690> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c67fa50>).
22/08/2020 01:31:53 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c67f650> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c69a6d0>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c684590> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7ff11c686a90>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff11c69a590> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c6b2cd0>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c6aa0d0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c673950>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff1440b6cd0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c610d90>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff1440ae8d0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c653c90>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c5f9f10> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c66cd50>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c6156d0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7ff11c637710>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff11c62db50> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c5d6b90>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c5cd8d0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c5a1690>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c5d7bd0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c542a10>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7ff11c5efad0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7ff11c547210>).
22/08/2020 01:31:54 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c593410> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7ff11c547650>).
22/08/2020 01:32:06 AM  start training
22/08/2020 01:33:03 AM  start training
22/08/2020 01:33:19 AM  Speed: 0.07281 img/second, 2
22/08/2020 01:33:21 AM  Speed: 0.55518 img/second, 3
22/08/2020 01:33:27 AM  start training
22/08/2020 01:33:43 AM  Speed: 0.07849 img/second, 4
22/08/2020 01:33:47 AM  Speed: 0.25561 img/second, 5
22/08/2020 01:33:50 AM  Speed: 0.49015 img/second, 6
22/08/2020 01:33:53 AM  Speed: 0.41493 img/second, 7
22/08/2020 01:33:56 AM  Speed: 0.49868 img/second, 8
22/08/2020 01:33:59 AM  Speed: 0.47059 img/second, 9
22/08/2020 01:34:04 AM  Speed: 0.21962 img/second, 10
22/08/2020 01:34:07 AM  Speed: 0.43668 img/second, 11
22/08/2020 01:34:10 AM  Speed: 0.40227 img/second, 12
22/08/2020 01:34:13 AM  Speed: 0.44275 img/second, 13
22/08/2020 01:34:16 AM  Speed: 0.44548 img/second, 14
22/08/2020 01:34:21 AM  Speed: 0.21223 img/second, 15
22/08/2020 01:34:25 AM  Speed: 0.38498 img/second, 16
22/08/2020 01:34:27 AM  Speed: 0.42897 img/second, 17
22/08/2020 01:34:30 AM  Speed: 0.44432 img/second, 18
22/08/2020 01:34:34 AM  Speed: 0.40714 img/second, 19
22/08/2020 01:34:39 AM  Speed: 0.20554 img/second, 20
22/08/2020 01:34:42 AM  Speed: 0.44654 img/second, 21
22/08/2020 01:34:45 AM  Speed: 0.48716 img/second, 22
22/08/2020 01:34:48 AM  Speed: 0.45212 img/second, 23
22/08/2020 01:39:34 AM  start training
22/08/2020 01:39:51 AM  Speed: 0.07369 img/second, 24
22/08/2020 01:39:56 AM  Speed: 0.23456 img/second, 25
22/08/2020 01:39:58 AM  Speed: 0.4913 img/second, 26
22/08/2020 01:40:01 AM  Speed: 0.47139 img/second, 27
22/08/2020 01:40:04 AM  Speed: 0.45188 img/second, 28
22/08/2020 01:40:07 AM  Speed: 0.46294 img/second, 29
22/08/2020 01:40:12 AM  Speed: 0.22591 img/second, 30
22/08/2020 01:40:15 AM  Speed: 0.43585 img/second, 31
22/08/2020 01:40:18 AM  Speed: 0.53969 img/second, 32
22/08/2020 01:40:20 AM  Speed: 0.46947 img/second, 33
22/08/2020 01:40:23 AM  Speed: 0.53196 img/second, 34
22/08/2020 01:40:28 AM  Speed: 0.21993 img/second, 35
22/08/2020 01:40:31 AM  Speed: 0.48294 img/second, 36
22/08/2020 01:40:34 AM  Speed: 0.50258 img/second, 37
22/08/2020 01:40:36 AM  Speed: 0.55177 img/second, 38
22/08/2020 01:40:39 AM  Speed: 0.4784 img/second, 39
22/08/2020 01:48:14 AM  start training
22/08/2020 01:49:40 AM  start training
22/08/2020 01:49:57 AM  Speed: 0.06536 img/second, 2
22/08/2020 01:49:59 AM  Speed: 0.95522 img/second, 3
22/08/2020 01:50:01 AM  Speed: 0.95498 img/second, 4
22/08/2020 01:50:03 AM  Speed: 0.56639 img/second, 5
22/08/2020 01:50:05 AM  Speed: 0.95849 img/second, 6
22/08/2020 01:50:07 AM  Speed: 0.94445 img/second, 7
22/08/2020 01:50:09 AM  Speed: 0.95728 img/second, 8
22/08/2020 01:50:12 AM  Speed: 0.93312 img/second, 9
22/08/2020 01:51:02 AM  start training
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c3b6110> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2896acc110>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2896acc110> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c374850>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c374850> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2895b12150>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2890264d90> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c342b50>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2895b12150> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c364d90>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c342b50> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c305b50>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2895ba1450> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c3d3bd0>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c364d90> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c368ad0>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c305b50> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c2e57d0>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2890274c10> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c282c90>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c3d3bd0> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c2aa410>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c368ad0> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c2a6d90>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c2db490> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c2b97d0>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c2e57d0> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c203f10>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c282c90> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c228e90>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c287190> and <tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c1b2790>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c2aa410> and <tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f280c1e1610>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.DepthwiseConv2D object at 0x7f280c2a6d90> and <tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f280c19afd0>).
22/08/2020 01:51:04 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c246e10> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f280c144350>).
22/08/2020 01:51:38 AM  start training
22/08/2020 01:52:34 AM  start training
22/08/2020 01:53:23 AM  start training
22/08/2020 01:53:54 AM  start training
22/08/2020 01:53:58 AM  Model was constructed with shape (None, 256, 256, 3) for input Tensor("input_2:0", shape=(None, 256, 256, 3), dtype=float32), but it was called on an input with incompatible shape (1, 128, 128, 3).
22/08/2020 01:53:59 AM  Model was constructed with shape (None, 256, 256, 3) for input Tensor("input_2:0", shape=(None, 256, 256, 3), dtype=float32), but it was called on an input with incompatible shape (1, 128, 128, 3).
22/08/2020 01:54:00 AM  Model was constructed with shape (None, 256, 256, 3) for input Tensor("input_2:0", shape=(None, 256, 256, 3), dtype=float32), but it was called on an input with incompatible shape (1, 128, 128, 3).
22/08/2020 01:54:21 AM  start training
22/08/2020 01:55:12 AM  start training
22/08/2020 01:55:56 AM  start training
22/08/2020 01:56:51 AM  start training
22/08/2020 01:58:26 AM  start training
22/08/2020 02:00:02 AM  start training
22/08/2020 02:00:27 AM  start training
22/08/2020 02:00:46 AM  Speed: 0.0594 img/second, 2
22/08/2020 02:00:48 AM  Speed: 0.97915 img/second, 3
22/08/2020 02:00:50 AM  Speed: 0.96039 img/second, 4
22/08/2020 02:00:52 AM  Speed: 0.5873 img/second, 5
22/08/2020 02:00:54 AM  Speed: 0.9758 img/second, 6
22/08/2020 02:00:56 AM  Speed: 0.9687 img/second, 7
22/08/2020 02:00:58 AM  Speed: 0.97395 img/second, 8
22/08/2020 02:01:00 AM  Speed: 0.96965 img/second, 9
22/08/2020 02:01:04 AM  Speed: 0.69311 img/second, 10
22/08/2020 02:01:06 AM  Speed: 0.97601 img/second, 11
22/08/2020 02:01:10 AM  Speed: 0.97068 img/second, 12
22/08/2020 02:01:13 AM  Speed: 0.97654 img/second, 13
22/08/2020 02:01:16 AM  Speed: 0.96883 img/second, 14
22/08/2020 02:01:19 AM  Speed: 0.72763 img/second, 15
22/08/2020 02:01:22 AM  Speed: 0.96219 img/second, 16
22/08/2020 02:01:25 AM  Speed: 0.9617 img/second, 17
22/08/2020 02:01:28 AM  Speed: 0.95947 img/second, 18
22/08/2020 02:01:32 AM  Speed: 0.97058 img/second, 19
22/08/2020 02:01:35 AM  Speed: 0.72487 img/second, 20
22/08/2020 02:01:37 AM  Speed: 0.97456 img/second, 21
22/08/2020 02:03:13 AM  start training
22/08/2020 02:03:25 AM  start training
22/08/2020 02:04:05 AM  start training
22/08/2020 02:04:14 AM  Speed: 0.1132 img/second, 2
22/08/2020 02:04:16 AM  Speed: 1.06899 img/second, 3
22/08/2020 02:04:34 AM  start training
22/08/2020 02:04:35 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f6348046210> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7f6328440a50>).
22/08/2020 02:04:35 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f63e9090250> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7f632844c890>).
22/08/2020 02:04:50 AM  start training
22/08/2020 02:05:00 AM  Speed: 0.12107 img/second, 4
22/08/2020 02:06:23 AM  start training
22/08/2020 02:06:24 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f6a9820f790> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7f6a981a3ed0>).
22/08/2020 02:06:24 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f6ad86d8c90> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7f6a981ac710>).
22/08/2020 02:06:39 AM  start training
22/08/2020 02:06:40 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f255409ca10> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7f2554093b50>).
22/08/2020 02:06:40 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f25e3c72ad0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x7f255409ccd0>).
22/08/2020 02:07:13 AM  start training
22/08/2020 02:08:49 AM  start training
22/08/2020 02:11:08 AM  start training
22/08/2020 02:12:05 AM  start training
22/08/2020 02:12:21 AM  start training
22/08/2020 02:12:41 AM  start training
22/08/2020 02:12:48 AM  Speed: 0.15991 img/second, 2
22/08/2020 02:12:50 AM  Speed: 1.07414 img/second, 3
22/08/2020 02:12:51 AM  Speed: 1.06746 img/second, 4
22/08/2020 02:12:53 AM  Speed: 0.66657 img/second, 5
22/08/2020 02:13:03 AM  start training
22/08/2020 02:13:05 AM  Model was constructed with shape (None, 128, 128, 3) for input Tensor("input_1:0", shape=(None, 128, 128, 3), dtype=float32), but it was called on an input with incompatible shape (1, 120, 120, 3).
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).disopti.iter
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).disopti.beta_1
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).disopti.beta_2
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).disopti.decay
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).disopti.learning_rate
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).genopti.iter
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).genopti.beta_1
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).genopti.beta_2
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).genopti.decay
22/08/2020 02:13:05 AM  Unresolved object in checkpoint: (root).genopti.learning_rate
22/08/2020 02:13:05 AM  A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
22/08/2020 02:13:12 AM  start training
22/08/2020 02:13:14 AM  Model was constructed with shape (None, 128, 128, 3) for input Tensor("input_1:0", shape=(None, 128, 128, 3), dtype=float32), but it was called on an input with incompatible shape (1, 120, 120, 3).
22/08/2020 02:13:30 AM  start training
22/08/2020 02:20:39 AM  start training
22/08/2020 02:20:58 AM  start training
22/08/2020 02:21:11 AM  start training
22/08/2020 02:21:13 AM  Model was constructed with shape (None, 128, 128, 3) for input Tensor("input_1:0", shape=(None, 128, 128, 3), dtype=float32), but it was called on an input with incompatible shape (1, 104, 104, 3).
22/08/2020 02:21:47 AM  start training
22/08/2020 02:21:49 AM  Model was constructed with shape (None, 128, 128, 3) for input Tensor("input_1:0", shape=(None, 128, 128, 3), dtype=float32), but it was called on an input with incompatible shape (1, 120, 120, 3).
22/08/2020 02:21:53 AM  start training
22/08/2020 02:22:03 AM  start training
22/08/2020 02:22:13 AM  Speed: 0.11263 img/second, 2
22/08/2020 02:22:15 AM  Speed: 1.05998 img/second, 3
22/08/2020 02:22:17 AM  Speed: 1.04944 img/second, 4
22/08/2020 02:22:19 AM  Speed: 0.65769 img/second, 5
22/08/2020 02:22:33 AM  start training
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).save_counter
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).disopti.iter
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).disopti.beta_1
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).disopti.beta_2
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).disopti.decay
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).disopti.learning_rate
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).genopti.iter
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).genopti.beta_1
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).genopti.beta_2
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).genopti.decay
22/08/2020 02:22:35 AM  Unresolved object in checkpoint: (root).genopti.learning_rate
22/08/2020 02:22:35 AM  A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
22/08/2020 02:22:49 AM  start training
22/08/2020 02:37:11 AM  start training
22/08/2020 02:37:20 AM  Speed: 0.12504 img/second, 2
22/08/2020 02:37:21 AM  Speed: 1.07677 img/second, 3
22/08/2020 02:37:23 AM  Speed: 1.05618 img/second, 4
22/08/2020 02:42:04 AM  start training
22/08/2020 02:42:14 AM  Speed: 0.11405 img/second, 5
22/08/2020 02:42:16 AM  Speed: 1.07903 img/second, 6
22/08/2020 02:42:18 AM  Speed: 1.06351 img/second, 7
22/08/2020 02:42:19 AM  Speed: 1.06702 img/second, 8
22/08/2020 02:42:21 AM  Speed: 1.06992 img/second, 9
22/08/2020 02:42:50 AM  start training
22/08/2020 02:42:51 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f9a6813bf50> and <tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f9a68146b50>).
22/08/2020 02:42:51 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f9a68146b50> and <tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f9a680eb750>).
22/08/2020 02:42:51 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f9a680eb750> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f9a681171d0>).
22/08/2020 02:43:09 AM  start training
22/08/2020 02:43:10 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f1b48117b90> and <tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f1af06ea110>).
22/08/2020 02:43:10 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f1af06ea110> and <tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f1af06a58d0>).
22/08/2020 02:43:10 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x7f1af06a58d0> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f1af06d3690>).
22/08/2020 02:43:19 AM  start training
22/08/2020 02:43:28 AM  Speed: 0.12314 img/second, 2
22/08/2020 02:43:29 AM  Speed: 1.05024 img/second, 3
22/08/2020 02:43:31 AM  Speed: 1.04226 img/second, 4
22/08/2020 02:43:33 AM  Speed: 0.69118 img/second, 5
22/08/2020 02:43:35 AM  Speed: 1.02741 img/second, 6
22/08/2020 02:43:37 AM  Speed: 1.0436 img/second, 7
22/08/2020 02:43:38 AM  Speed: 1.03286 img/second, 8
22/08/2020 02:43:40 AM  Speed: 1.02851 img/second, 9
22/08/2020 02:43:42 AM  Speed: 0.83446 img/second, 10
22/08/2020 02:43:44 AM  Speed: 1.03116 img/second, 11
22/08/2020 02:43:46 AM  Speed: 1.03701 img/second, 12
22/08/2020 05:23:23 AM  start training
22/08/2020 05:23:24 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f23723fc790> and <tensorflow.python.keras.layers.merge.Add object at 0x7f235c1398d0>).
22/08/2020 05:23:24 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f23180e6dd0> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f23723fc790>).
22/08/2020 05:23:24 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f231808b550> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f23180e6dd0>).
22/08/2020 05:23:24 AM  Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f2318070f50> and <tensorflow.python.keras.layers.merge.Add object at 0x7f2318072790>).
22/08/2020 05:23:33 AM  start training
22/08/2020 05:23:45 AM  Speed: 0.10672 img/second, 2
22/08/2020 05:23:47 AM  Speed: 1.17356 img/second, 3
22/08/2020 05:23:48 AM  Speed: 1.15601 img/second, 4
22/08/2020 05:23:51 AM  Speed: 0.73255 img/second, 5
22/08/2020 05:23:53 AM  Speed: 1.14113 img/second, 6
22/08/2020 05:23:55 AM  Speed: 1.16165 img/second, 7
22/08/2020 05:23:56 AM  Speed: 1.17403 img/second, 8
22/08/2020 05:23:58 AM  Speed: 1.16276 img/second, 9
22/08/2020 05:24:00 AM  Speed: 0.8482 img/second, 10
22/08/2020 05:24:02 AM  Speed: 1.1568 img/second, 11
27/09/2020 03:35:38 AM  start training
27/09/2020 03:37:27 AM  start training
27/09/2020 03:38:24 AM  start training
27/09/2020 03:40:44 AM  start training
27/09/2020 03:40:54 AM  Speed: 0.11512 img/second, 2
27/09/2020 03:40:57 AM  Speed: 0.40944 img/second, 3
27/09/2020 03:41:00 AM  Speed: 0.40495 img/second, 4
27/09/2020 03:41:07 AM  Speed: 0.13852 img/second, 5
27/09/2020 03:41:11 AM  Speed: 0.39353 img/second, 6
27/09/2020 03:41:29 AM  start training
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).disopti.iter
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).disopti.beta_1
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).disopti.beta_2
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).disopti.decay
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).disopti.learning_rate
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).genopti.iter
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).genopti.beta_1
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).genopti.beta_2
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).genopti.decay
27/09/2020 03:41:32 AM  Unresolved object in checkpoint: (root).genopti.learning_rate
27/09/2020 03:41:32 AM  A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
27/09/2020 03:44:40 AM  start training
27/09/2020 03:44:42 AM  From /home/hackerton/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
27/09/2020 03:48:18 AM  start training
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).disopti.iter
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).disopti.beta_1
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).disopti.beta_2
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).disopti.decay
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).disopti.learning_rate
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).genopti.iter
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).genopti.beta_1
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).genopti.beta_2
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).genopti.decay
27/09/2020 03:48:20 AM  Unresolved object in checkpoint: (root).genopti.learning_rate
27/09/2020 03:48:20 AM  A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
27/09/2020 03:49:10 AM  start training
27/09/2020 03:49:12 AM  From /home/hackerton/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
27/09/2020 03:49:40 AM  start training
27/09/2020 03:49:42 AM  From /home/hackerton/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
27/09/2020 03:51:00 AM  start training
27/09/2020 03:51:02 AM  From /home/hackerton/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
27/09/2020 03:52:42 AM  start training
27/09/2020 03:52:44 AM  From /home/hackerton/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
27/09/2020 03:53:01 AM  Speed: 0.54913 img/second, 8
27/09/2020 03:53:20 AM  Speed: 0.55018 img/second, 10
27/09/2020 03:53:32 AM  Speed: 0.9205 img/second, 12
